name: docker-pipeline-govarthini
on: push
jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print your Register Number
        run: echo "HelloÂ World-22IT009!"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Build
        run: docker build -t govarthini240/ml-model-22it009 .
      - name: Docker Images
        run: docker images
